name: CI
on:
  push:
    branches:
      ['**']
  pull_request:
    branches:
      ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Say hello
        run: echo "Hello world"
      - name: Run unit tests
        run: npm test
  
  
