on:
  workflow_dispatch:
  
name: Print Stuff

env: 
  TEST: '{"name": "sveta"}'

jobs:
  print:
    runs-on: ubuntu-latest
    steps: 
      - name: Dump GitHub context 
        run: | 
            echo "${{toJson(env.TEST)['name']}}"
