on:
  workflow_dispatch:
  
name: Print Stuff

jobs:
  print:
    runs-on: ubuntu-16.04 
    steps: 
      - name: Dump GitHub context 
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }} 
        run: echo "$GITHUB_CONTEXT" 
