on:
  workflow_dispatch:
  
name: Print Stuff

env: 
  TEST: '{"name": "sveta"}'
  SOME_KEY: "name"

jobs:
  print:
    runs-on: ubuntu-latest
    steps: 
      - name: Dump GitHub context 
        run: | 
            echo "${{fromJSON(env.TEST)[env.SOME_KEY]}}"
