on:
  workflow_dispatch:
  
name: Print Stuff

jobs:
  print:
    runs-on: ubuntu-latest
    steps: 
      - name: Dump GitHub context 
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }} 
          SOME_KEY: 'job'
        run: | 
            echo "${{env.GITHUB_CONTEXT[env.SOME_KEY]}}"
