name: Test string replace
on:
    workflow_dispatch:
        inputs:
            version:
                description: "version number to deploy"
                required: true
                type: string


jobs:
    do-stuff:
        runs-on: ubuntu-latest
        outputs:
            version_number: ${{ steps.replace-string.outputs.replaced }}
        steps:
          - uses: frabert/replace-string-action@v2
            id: replace-string
            with:
              pattern: '(ver)?(\d+)'
              string: ${{ inputs.version }}
              replace-with: '$2'
          - name: "print"
            run: echo ${{steps.replace-string.outputs.replaced}}
    do-stuff-2:
        needs: [do-stuff]
        runs-on: ubuntu-latest
        steps:
          - name: "print in another job"
            run: |
                echo ${{needs.do-stuff.outputs.version_number}}
        
      
