name: Test string replace
on:
    workflow_dispatch:
        inputs:
            version:
                description: "version number to deploy"
                required: true
                type: string


jobs:
    do-stuff:
        runs-on: ubuntu-latest
        steps:
          - uses: frabert/replace-string-action@v2
            id: replace-string
            with:
              pattern: '(ver)?(\d+)'
              string: ${{ inputs.version }}
              replace-with: '$2'
          - name: "print"
            run: echo ${{steps.replace-string.outputs.replaced}}
          - name: "Set new env param"
            run: |
             echo "version_number=${{steps.replace-string.outputs.replaced}}" >> $GITHUB_ENV
             echo "version_number={steps.replace-string.outputs.replaced}" >> $GITHUB_OUTPUT
          - name: "print2"
            run: echo ${{env.version_number}}
    do-stuff-2:
        needs: [do-stuff]
        runs-on: ubuntu-latest
        steps:
          - name: "print in another job"
            run: |
                echo ${{env.version_number}}
                echo ${{needs.do-stuff.outputs.version_number}}
        
      
